
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayFabDataStore : MonoBehaviour
{
    public static string playFabID;
    //public static string playerName;
    //public static string playerActiveSkin;
    public static string gameMode = "Deathmatch";
    public static int deathmatchFinalScore = 20;
    public static PlayerBaseStats playerBaseStats;
    public static PlayerProfile playerProfile;
    public static Dictionary<string, int> playerStatistics = new Dictionary<string, int>()
    {
        {"Games Played", 0 },
        {"Lifetime Kills", 0 },
        {"Deaths", 0 },
        {"Kill Streak", 0 },
        {"Deathmatch Win", 0 }
    };
    public static Dictionary<string, SkinModel> playerSkins = new Dictionary<string, SkinModel>();
    public static Dictionary<string, SkinModel> gameSkinCatalog = new Dictionary<string, SkinModel>();
    public static int vc_gems;
    public static int vc_coins;
    public static int vc_energy;
    public static int vc_adGem;
    public static int vc_adCoin;
    public static int adGemRechargeTime;
    public static int adCoinRechargeTime;
    public static bool gameCenterLinked = false;

    public static string[] botNames =
    {"FoNite",
    "NiteFort",
    "DorkNite",
    "FortBites",
    "FortHype",
    "Fortex",
    "Forex",
    "AFortniteADay",
    "CantAFortThis",
    "MySummerVacation",
    "RoyaleWCheese",
    "BattleMyPal",
    "FortU",
    "FortOff",
    "Fortov",
    "ForkFight",
    "VBuckeroo",
    "SaveTheFort",
    "Foritiswritten",
    "ForScore",
    "Maiden",
    "Catastrophe",
    "HiddenKiss",
    "MissWhiteRose",
    "GorgeousGamer",
    "HotChocolate",
    "Fortnight",
    "ForTonight",
    "TwoWeeks",
    "TwoWeeksTillXmas",
    "2Weeks2Live",
    "TooWeak",
    "14Days",
    "Fourteennights",
    "Biweekly",
    "FortKnight",
    "KnightsOfThaFort",
    "FortyKnights",
    "Forty-fourNights",
    "TheRoundtable",
    "FawltyTowers",
    "FortniteGod",
    "FortniteGoddess",
    "FortniteGirl",
    "FortniteGal",
    "PillowFort",
    "MattressFort",
    "BoxFort",
    "FortLauderdale",
    "TheGirlWhoDumpedU",
    "Confusedgirl",
    "EstroJen",
    "DopeySuperwoman",
    "NotAnotherGamerGirl",
    "Spokeswomen",
    "HippoBottom",
    "Gamergirl",
    "Blush",
    "BlushingTokki",
    "MaryPoppins",
    "BabiiCakezz",
    "Sp0use",
    "TeaCupCake7",
    "WheresPeterPan",
    "Skybby",
    "PrincessGunfire",
    "KatKnip",
    "Kitteh Power",
    "MamaKitty",
    "MeowMix",
    "KittenForVictory",
    "K1TT3NSnK1LLS",
    "BubbleHearts",
    "Friendette",
    "SleepingBeauty",
    "GamingBeauty",
    "LovelyKiller",
    "SquirrelPower",
    "blosSomP!nK",
    "AstroGirl",
    "MisFit",
    "MissNeverLand",
    "QtPie",
    "Beastings",
    "SmittenKitten",
    "UKittenMe",
    "MidnightKitty",
    "LaLaLand",
    "ScarfFace",
    "DillyDally",
    "MissChief",
    "AngelBunny",
    "Goldilocks",
    "LilRedRiddingHood",
    "ZebraCakes",
    "BettyBoop",
    "GlitterR0CkZ",
    "Dominatrix",
    "KissOfDeathAim",
    "MissGirlGuns",
    "GeekGirl",
    "MeanGirl",
    "RunLikeAGirl",
    "PlayLikeAGirl",
    "KillLikeAGirl",
    "Misdemeanor",
    "AppleBottoms",
    "AppleBottomJeans",
    "murda",
    "GirlsPwn",
    "WarGoddess",
    "ManiakChikk",
    "TheDevilWearsPrada",
    "XxD3V1LxG1RLxX",
    "Chiefette",
    "GurlyGurl",
    "CantTouchThis",
    "Miss Glock&heels",
    "Beat By A Girl",
    "BeatMyALady",
    "MurderedByAGirl",
    "VictoryOverBoys",
    "UGotRektByAChick",
    "LaGamer",
    "ScaryNinja",
    "NinjaHype",
    "Shuriken",
    "NinjaStar",
    "EnterTheNinja",
    "EnterTheDragon",
    "Metsubishi",
    "Pandas",
    "OpaqueNinja",
    "Manriki-gusari",
    "NinjaMan",
    "NinjaDude",
    "Silent assassin",
    "Kunai",
    "Ninjah",
    "TwoKatanas",
    "KatanaIfyawanna",
    "KantanaSlice",
    "KantanaOnToast",
    "Precursorninja",
    "NinjaSkills",
    "Skillslikeaninja",
    "NinjaOnFire",
    "Fukiya",
    "Ninja Maneuver",
    "Ninjamoves",
    "Ninja Pwnage",
    "Neko Te",
    "NekoTeGirl",
    "NekoTeClaws",
    "NinjaWithWings",
    "TMNT",
    "Shredder",
    "Justturtles",
    "Kakute",
    "NinjaSchool",
    "NowYouSeeMe",
    "Kusarigama",
    "Wayofthewarrior",
    "Callmesensei",
    "Samureye",
    "SamuraiJack",
    "ShadowFriend",
    "ShadowFiend",
    "CrouchingTiger",
    "Whatisninja",
    "Ninjutsu",
    "Revenge",
    "Avenged",
    "Alley Frog",
    "Alpha",
    "AlphaReturns",
    "Angel",
    "AngelsCreed",
    "Arsenic Coo",
    "Atomic Blastoid",
    "Automatic Slicer",
    "Baby Brown",
    "Back Bett",
    "Bad Bunny",
    "Bazooka Har-de-har",
    "Bearded Angler",
    "Beetle King",
    "Betty Cricket",
    "Bit Sentinel",
    "Bitmap",
    "BlacKitten",
    "Blister",
    "Blistered Outlaw",
    "Blitz",
    "Bug Fire",
    "Bugger",
    "Cabbie",
    "Candy Butcher",
    "Capital F",
    "Captain Peroxide",
    "Celtic Charger",
    "Criss Cross",
    "Cross Thread",
    "Cujo",
    "Cupid Dust",
    "Dropkick",
    "FireByMisFire",
    "Fist Wizard",
    "Flakes",
    "Greek Rifle",
    "Jester",
    "JesterZilla",
    "JigKraken",
    "Knuckles",
    "Lord Pistachio",
    "Manimal",
    "Nickname Master",
    "ScaryNinja",
    "ScaryPumpkin",
    "Scrapper",
    "Scrapple"};

}
